### ISSUE TITLE
chore(simapp): discuss usefulness of simapp

### ISSUE THREAD

**Issue by NibiruHeisenberg** [NibiruChain/nibiru#1057]
@testinginprod : maybe a development branch is better than having to deal with two different apps in the codebase

**Comment by Unique-Divine** [comment]
I would like to delete the simapp

**Comment by Unique-Divine** [comment]
For historical context, our `simapp` directory used to maintain an entirely separate ABCI base app: [simapp/app.go (Nov 2022)](https://github.com/NibiruChain/nibiru/blob/4ba2a5c57a5fa6a912dbc2d5195288bb11cc1b8f/simapp/app.go) 

At some point, we cleaned this up so that the `simapp` is only used for `sim` (simulations), how it should be.
