### ISSUE TITLE
feat(vpool): maintenance margin ratio should be modifiable by governance

### ISSUE THREAD

**Issue by NibiruHeisenberg** [NibiruChain/nibiru#1065]
### Task Summary
- [x] Since maintenance margin ratio is an attribute of a `Vpool`, it can be removed from the genesis.
- [x] Add tx to edit vpools

**Comment by Unique-Divine** [comment]
### Suggestion

We should make this a parameter of the virtual pool rather than the module. It's common for different asset pairs to have different maximum leverage on [larger exchanges](https://www.binance.com/en/margin-data). Different position change magnitudes can also factor into this.

### Benchmark - Binance

| Pair | Tier | Max Leverage | 
| --- | --- | --- |
| BTC/USDT |	1 | 	10x |
| BTC/DAI |	1 | 	3x	 |
| AAVE/BTC |	1 | 	5x |
| BNB/USDT |	1 | 	10x |
| DOT/BUSD |	1 | 	5x |
| ATOM/ETH |	1 | 	3x |
| ATOM/BUSD |	1 | 	5x |

References:
- [Isolated Margin Data Tables. Binance.](https://www.binance.com/en/margin-data) | (current leverage tiers)
- [Updates on Leverage and Margin Tiers of Binance Futures Contracts (2021-08-18). Binance.](https://www.binance.com/en/support/announcement/updates-on-leverage-and-margin-tiers-of-binance-futures-contracts-2021-08-18-34801a0c405a4b058f9ae18a1a34cad3)

### Benchmark - dYdX

| Asset | Leverage Limit | 
| -- | -- |
| BTC | 20x |
| ETH | 20x |
| All Other Markets | 10x | 

Reference: [Maximum Leverage for Perpetuals. dYdX](https://help.dydx.exchange/en/articles/4797403-maximum-leverage-for-perpetuals)

### Benchmark - Huobi 

> "Huobi Futures support 1x-100x leverage"

Reference: [Contract Leverage Introduction](https://www.huobi.com/support/en-us/detail/44892511689070)

@NibiruChain/backend

**Comment by Unique-Divine** [comment]
Sounds like the objective of this issue is to simply delete it from the perp module params then
