### ISSUE TITLE
[AUDIT] sender field is not checked for wasm

### ISSUE THREAD

**Issue by matthiasmatt** [NibiruChain/nibiru#1378]
The sender field for all the wasm custom messages can be set to an arbitrary address allowing you to open/close or add/remove margin for anyone using their coins

---

### Tasks

- [x] https://github.com/NibiruChain/cw-nibiru/pull/30
- [x] fix(wasm): Make sure that AddMargin, RemoveMargin, OpenPosition, ClosePosition, Donate, etc. are permissioned with `x/sudo` to enforce the sender | #1222

**Comment by Unique-Divine** [comment]
More info: The `DispatchMsg` doesn't have access to the address when the message comes through, so it operates a bit different than `[]sdk.Message` types that come through an `sdk.Handler`, and the `sender` field would have to be enforced in another manner.

### Recommended Solution

Use the `x/sudo` pattern that the `shifter` and `controller` contracts use for `perp-bindings`. This allows the contract to set the field for the `sender` in its execution entry point rather than the caller of the method.

### Example fix:

Here's the original `ClosePosition` execution path on the `bindings-perp` contract we have right now.

```rust
#[entry_point]
pub fn execute(
    _deps: DepsMut<QueryPerpMsg>,
    _env: Env,
    _info: MessageInfo,
    msg: ExecuteMsg,
) -> StdResult<Response<NibiruExecuteMsg>> {
    match msg {
        // ...
        ExecuteMsg::ClosePosition { sender, pair } => nibiru_msg_to_cw_response(
            NibiruExecuteMsg::close_position(sender, pair),
        ),
```
 
Here's what we should put instead to remove the `sender` as an argument:

```rust
#[entry_point]
pub fn execute(
    _deps: DepsMut<QueryPerpMsg>,
    _env: Env,
    info: MessageInfo, // ← make info a used variable
    msg: ExecuteMsg,
) -> StdResult<Response<NibiruExecuteMsg>> {
    match msg {
        // ...
        ExecuteMsg::ClosePosition { pair } => {  // ← remove sender here
            let sender: Addr = info.sender;  // ← grab sender from msg
            nibiru_msg_to_cw_response(
            NibiruExecuteMsg::close_position(sender, pair),
          ),
        }
```

**Comment by Unique-Divine** [comment]
Closed by https://github.com/NibiruChain/cw-nibiru/pull/30
