### ISSUE TITLE
bug(perp): MsgMultiLiquidateResponse is missing a pair

### ISSUE THREAD

**Issue by onikonychev** [NibiruChain/nibiru#1456]
Can't determine a liquidated position without it.

**Comment by k-yang** [comment]
`MsgMultiLiquidateResponse` doesn't need a `pair` because it's an aggregation of multiple liquidate requests, each of which can target a different pair/trader combination. The index of the `MsgMultiLiquidateResponse_LiquidationResponse` matches up with each of the liquidation requests in the `MsgMultiLiquidateRequest`.
